version: '3.7'

services:
  app:
    image: node:20.13.1
    container_name: lets-help-rs-backend
    user: 'root'
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@lets-help-rs-database:5432/letshelprs"
    command: bash -c "npm i --legacy-peer-deps; npm i -g @nestjs/cli; npm run start:dev"
    ports:
      - "3000:3000"
    networks:
      - web

  db:
    container_name: lets-help-rs-database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: letshelprs
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - web

networks:
  web:
    external: true

volumes:
  db_data:
