version: '3.7'

services:
  app:
    image: phmarquesdev/lets-help-rs-backend:latest
    container_name: lets-help-rs-backend
    user: 'root'
    restart: always
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - DB_PROVIDER=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=letshelprs
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_SCHEMA=public
      - DATABASE_URL=postgresql://postgres:admin@db:5432/letshelprs
      - DATABASE_URL_WITH_SCHEMA=postgresql://postgres:admin@db:5432/letshelprs?schema=public
      - NODE_ENV=development
      - SERVER_PORT=3000
      - CREATION_ACCURACY_RADIUS_IN_DEGREES=0.005
      - LOCALIZATION_ACCURACY_RADIUS_IN_DEGREES=0.3
      - REPORT_DELETE=10
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.letshelprs.online`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - web

  db:
    container_name: lets-help-rs-database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: letshelprs
    networks:
      - web

networks:
  web:
    external: true
