name: Deploy API to VPS

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: lets-help-rs/lets-help-rs-api
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push api image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/lets-help-rs-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/lets-help-rs-api:latest

      - name: SSH to server and update api container
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd ~/letshelpRS/lets-help-rs-api

            # Fetch the latest commit hash
            LATEST_VPS_COMMIT=$(git rev-parse HEAD)

            # Get the current commit hash in the workflow
            CURRENT_COMMIT=$(git rev-parse HEAD)

            # Compare the two commit hashes
            if [ "$LATEST_VPS_COMMIT" == "$CURRENT_COMMIT" ]; then
              echo "No changes detected. Stopping the workflow."
              echo "::set-output name=changes_detected::false"
              exit 1
            else
              echo "Changes detected. Continuing with the workflow."
              echo "::set-output name=changes_detected::true"
              docker compose pull api
              docker compose up -d api
            fi
